//TETS DEVELOPEMENTE

// 1)CREAR PRUEBA CON FUNCIONALIDAES QUE SE NECESSAR
// 2)ESCRIBIR EL CODIGO PARA PASAR LA PRUEBA CON FUNCIONALIDADES
// 3)REFACTORIZAR EL CODIGO PARA QUE SE PASEN LAS PRUEBAS Y MEJORE EL CODIGO
//USAMOS BUSCAR EL JEST TEST JAVASCRIPT PARA PASAR LAS PRUEBAS